spring:
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL-AUTO}
    database-platform: ${SPRING_JPA_DATABASE-PLATFORM}
  datasource:
    url:  ${JDBC_DATABASE_URL}
    username:  ${SPRING_DATASOURCE_USERNAME}
    password:  ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource