spring:
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL-AUTO}
    database-platform: ${SPRING_JPA_DATABASE-PLATFORM}
  datasource:
    url:  ${JDBC_DATASOURCE_URL}
    username:  ${SPRING_DATASOURCE_USERNAME}
    password:  ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource
    tomcat:
      max-active: 10
      max-idle: 5
      min-idle: 2
      initial-size: 5
      remove-abandoned: true